### Ejercicio 4 - Investigar Como?

<div class="well">Crear un programa que permita hacer operaciones con matrices en <strong>Python</strong> utilizando los módulos <strong>NumPy</strong> y <strong>SciPy</strong> para resolver la inversa, la multiplicación y la solución de un sistema de ecuaciones lineales.


</div>


In [1]:
pip install numpy scipy imageio

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
from scipy.linalg import inv, solve

In [9]:
A = np.array([
    [10, -1, 2, 0],
    [-1, 11, -1, 3],
    [2, -1, 10, -1],
    [0, 3, -1, 8]
])

print("Matriz A:", A)

Matriz A: [[10 -1  2  0]
 [-1 11 -1  3]
 [ 2 -1 10 -1]
 [ 0  3 -1  8]]


In [10]:
B = np.array([
    [6, 5, 4, 2],
    [25, 10, 1, 20],
    [7, 9, 8, 2],
    [5, 1, 14, 2]
])

print("Matriz B:", B)

Matriz B: [[ 6  5  4  2]
 [25 10  1 20]
 [ 7  9  8  2]
 [ 5  1 14  2]]


In [11]:
A_inv = inv(A)

print("Inversa de A:", A_inv)

Inversa de A: [[ 0.10507099  0.00933063 -0.02068966 -0.00608519]
 [ 0.00933063  0.10250169  0.0045977  -0.03786342]
 [-0.02068966  0.0045977   0.10574713  0.01149425]
 [-0.00608519 -0.03786342  0.01149425  0.14063556]]


In [12]:
B_inv = inv(B)

print("Inversa de B:", B_inv)

Inversa de B: [[ 7.94285714e-01 -4.00000000e-02 -3.97142857e-01  2.85714286e-03]
 [-3.05714286e-01  1.00000000e-02  2.77857143e-01 -7.21428571e-02]
 [-1.42857143e-01  6.93889390e-18  7.14285714e-02  7.14285714e-02]
 [-8.32857143e-01  9.50000000e-02  3.53928571e-01  2.89285714e-02]]


In [13]:
AB = np.dot(A, B)
print("Multiplicación de A y B:")
print(AB)

Multiplicación de A y B:
[[ 49  58  55   4]
 [277  99  41 222]
 [ 52  89  73   2]
 [108  29 107  74]]


In [14]:
X = solve(A, B)
    
print("Solución del sistema A * X = B:", X)

Solución del sistema A * X = B: [[ 0.68843813  0.42636917  0.17890467  0.34320487]
 [ 2.46139283  1.07518594 -0.35348208  2.00216362]
 [ 0.78850575  0.90574713  0.92873563  0.28505747]
 [-0.19945909 -0.16497634  1.99864773 -0.46517918]]
