<center> <h1>Universidad Nacional de San Agustín de Arequipa</h1> </center> 
<center> <h1>Escuela Profesional de Ingeniería de Telecomunicaciones</h1> </center> 

<center> <h1> </h1> </center> 

<center><img src="https://user-images.githubusercontent.com/19308295/115939517-f1c6fe80-a463-11eb-989c-812ab4942586.png" width="380" height="4200"></center>

<center> <h2>Ingeniero Renzo Bolivar - Docente DAIE</h2> </center> 

<center> <h1>Curso : Computación 2</h1> </center> 

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)

<center> <h1>Numpy Matemático</h1> </center> 

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)

# Descripción:

En este notebook se explicarán los

# Objetivos:

algunas funciones importantes de pandas.

[1. Matemática Básica](#1.-Matemática-Básica)<br>
[2. Matemática Estadística](#2.-Matemática-Estadística)<br>
[3. Procesamiento de señal (scipy.signal)](#3.-Procesamiento-de-señal-(scipy.signal))<br>


[EJEMPLOS](#EJEMPLOS)<br>
[EJERCICIOS](#EJERCICIOS)<br>
[BIBLIOGRAFÍA](#BIBLIOGRAFÍA)<br>

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)

La caja de herramientas de procesamiento de señales actualmente contiene algunas funciones de filtrado, un conjunto limitado de herramientas de diseño de filtros y algunos algoritmos de interpolación `B-spline` para datos 1 y 2-D. 

Si bien los algoritmos `B-spline` podrían ubicarse técnicamente en la categoría de interpolación, se incluyen aquí porque solo funcionan con datos igualmente espaciados y hacen un uso intensivo de la teoría de filtros y el formalismo de la función de transferencia para proporcionar una transformación `B-spline` rápida. Para comprender esta sección, deberá comprender que una señal en SciPy es una matriz de números reales o complejos.

<div class="alert alert-info">Una función ideal para reconstruir muestras a partir de coeficientes de spline y es más rápida que convolve2d, lo que implica filtros arbitrarios en 2-D y permite elegir condiciones límite simétricas especulares.</div>

<div class="alert alert-info">Alternativamente, podríamos haber hecho:</div>

![linea 2](https://user-images.githubusercontent.com/19308295/115926262-2fb62980-a448-11eb-8189-c2f10e499944.png)

<div class="alert alert-info"> El <strong>filtrado</strong> es un nombre genérico para cualquier sistema que modifique una señal de entrada de alguna manera. En <strong>SciPy</strong>, una señal puede considerarse como una matriz <strong>NumPy</strong>. Existen diferentes tipos de filtros para diferentes tipos de operaciones.</div>

En ***Scipy*** `correlate` y/o `convolve` puede usarse para construir filtros de imagen arbitrarios para realizar acciones tales como desenfoque, mejora y detección de bordes para una imagen.

## <font color=#33A5FF>****EJERCICIOS****<tfont>

### Ejercicio 1 - Investigar Como?

#### Resolver las siguientes ecuaciones:


$$12x + 5y + z= 6$$
$$6x + 10y + z = 8$$
$$3x + 15y + z = 4$$



#### Utilizando un método diferente al enseñado  $A*x =B$

In [6]:
import numpy as np
import numpy.linalg as lin
A = np.array([
    [15,5,1],
    [6,10,1],
    [3,15,1]
])
B = np.array([
    [6],
    [8],
    [4]
])

print('La matriz A es: ')
print(A)
print('\nLa matriz B: ')
print(B)
print('\nLa matriz x , que sale al dividir la matriz B entre A, es: ')


La matriz A es: 
[[15  5  1]
 [ 6 10  1]
 [ 3 15  1]]

La matriz B: 
[[6]
 [8]
 [4]]

La matriz x , que sale al dividir la matriz B entre A, es: 


<div class="well">Crear un programa que permita hacer operaciones con matrices en <strong>Python</strong> utilizando los módulos <strong>NumPy</strong> y <strong>SciPy</strong> para resolver la inversa, la multiplicación y la solución de un sistema de ecuaciones lineales.


</div>


### Ejercicio 5 - Investigar Como?

<div class="well">Crear un programa que permita resolver una <strong>interpolación utilizando polinomios de Lagrange</strong> en Python <strong> SciPy </strong> .


</div>

In [7]:
from scipy.interpolate import lagrange 
def interpolacion_lagrange(x, y, x_eval):
    """
    Realizamos una interpolacion utilizando polinomios de Lagrange.

    Args:
        x(list): Lista de puntos x conocidos.
        y(list): Lista de puntos y conocidos.
        x_eval (float): Valor x en el que se desea evaluar el polinomio interpolante.
    Returns:
        float: Valor y obtenido mediante interpolacion en x_eval.
    """
    polinomio = lagrange(x, y)
    y_eval = polinomio(x_eval)
    return y_eval

# Ejemplo
x = [1,2,3,4,5]
y = [6,4,3,2,1]
x_eval = 2.5

resultado = interpolacion_lagrange(x, y, x_eval)
print("El valor interpolado en x =", x_eval, "es y =", resultado)

El valor interpolado en x = 2.5 es y = 3.4609375


![linea 2](https://user-images.githubusercontent.com/19308295/115926262-2fb62980-a448-11eb-8189-c2f10e499944.png)

## <font color=#33A5FF>****BIBLIOGRAFÍA****<tfont>

[1] Documentación de NumPy: https://numpy.org/doc/stable/

[2] Algebra líneal con NumPy web Pybonacci: https://pybonacci.org/2012/06/07/algebra-lineal-en-python-con-numpy-i-operaciones-basicas/

[3] Funciones de distribución de probabilidad en NumPy: https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html

[4] Algebra líneal en NumPy:https://numpy.org/doc/stable/reference/routines.linalg.html

[5] SymPy:https://www.sympy.org/en/index.html

[6] SciPy:https://www.scipy.org/

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)