<center> <h1>Universidad Nacional de San Agustín de Arequipa</h1> </center> 
<center> <h1>Escuela Profesional de Ingeniería de Telecomunicaciones</h1> </center> 

<center> <h1> </h1> </center> 

<center><img src="https://user-images.githubusercontent.com/19308295/115939517-f1c6fe80-a463-11eb-989c-812ab4942586.png" width="380" height="4200"></center>

<center> <h2>Ingeniero Renzo Bolivar - Docente DAIE</h2> </center> 

ALUMNA: Damaris Dana Lupaca Sancja

<center> <h1>Curso : Computación 2</h1> </center> 

![linea 2](https://user-images.githubusercontent.com/19308295/115926262-2fb62980-a448-11eb-8189-c2f10e499944.png)

## <font color=#33A5FF>****2. Numpy: Funciones básicas****<tfont>

###  Matriz  unidimensional

Con la primera instrucción `import numpy as np` le estamos indicando a nuestro programa de Python que de ahora en adelante `np` será la referencia para todo lo referente a NumPy.

In [4]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


###  Matriz bidimensional

In [5]:
b=np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
array=np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)
print(array)

[[1 2 3 4]
 [5 6 7 8]]


###  Porque usar NumPy

Porque usar NumPy en vez de utilizar las listas propias que ofrece Python para manejar estos datos, la primera razón es que NumPy ocupa menos memoria en comparación a las lista de Python, a su vez es bastante rápido en términos de ejecución. Lo que se observa en el siguiente ejemplo:

**Cantidad de memoria asignada**

In [7]:
import sys
S=range(1000)
print(sys.getsizeof(5)*len(S))

28000


In [8]:
D=np.arange(1000)
print(D.size * D.itemsize)

4000


**Velocidad**

In [9]:
import time
SIZE = 1000000

L1= range(SIZE)
L2= range(SIZE)

start= time.time()
result=[ (x,y) for x,y in zip(L1,L2)] #se usa for
print((time.time()-start)*1000) #velocidad en Listas

200.0269889831543


In [11]:
A1=np.arange(SIZE)
A2=np.arange(SIZE)
start=time.time()
result= A1+A2                     #solo se suma
print((time.time()-start*1000)) #velocidad de Numpy

-1715223584761.2944


### Matrices Vacias

En ocasiones se requiere crear matrices vacías, esto se refiere a que se requieren marcadores de posición iniciales, que luego pueden ser rellenados. Se puede inicializar matrices con unos o ceros, pero también puedes hacer matrices que se llenan con valores espaciados uniformemente, valores constantes o aleatorios.

Algunas de las instrucciones para crear este tipo de matrices son las siguientes:

**Crear una matriz en donde todos los valores sean igual a 1**

In [12]:
unos = np.ones((3,4))
print(unos)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**Crear una matriz en donde todos los valores sean igual a 0**

In [13]:
ceros = np.zeros((3,4))
print(ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Crear una matriz de números aleatorios**

In [14]:
aleatorios = np.random.random((2,2))
print(aleatorios)

[[0.46717118 0.48803307]
 [0.16947671 0.09480749]]


**Crear una matriz vacía**

In [15]:
vacia = np.empty((3,2))
vacia.fill(0)
print(vacia)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


**Crear una matriz que contenga un solo valor en todas las posiciones**

In [16]:
full = np.full((2,2),8)
print(full)

[[8 8]
 [8 8]]


**Crear una matriz con rangos de números**

In [17]:
espacio1 = np.arange(0,30,5)
print(espacio1)

[ 0  5 10 15 20 25]


In [18]:
espacio2 = np.linspace(0,2,5)
print(espacio2)

[0.  0.5 1.  1.5 2. ]


**Crear una matriz identidad**

In [19]:
identidad1 = np.eye(4,4)
print(identidad1)

identidad2 = np.identity(4)
print(identidad2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


![linea 2](https://user-images.githubusercontent.com/19308295/115926262-2fb62980-a448-11eb-8189-c2f10e499944.png)

## <font color=#33A5FF>****3. Inspeccionar matrices de NumPy****<tfont>

**Dimensión de una matriz**

In [20]:
# Conocer las dimensiones de una matriz
a = np.array([(1,2,3),(4,5,6)])
print(a.ndim)

2


**Tipo de Datos de una matriz**

In [21]:
# Conocer el tipo de los datos
print(a.dtype)

int32


**Tamaño y forma de una matriz**

In [22]:
# Conocer el tamaño y forma de la matriz
a = np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)

6
(1, 6)


**Cambio de forma de una matriz**

In [23]:
# Cambio de forma de una matriz
a = np.array([(8,9,10),(11,12,13)]) #2 filas x 3 columnas
print(a)
a=a.reshape(3,2) #3 filas x 2 columnas
print(a)

[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


**Seleccionar elemento de una matriz**

In [24]:
# Extraer un solo valor de la matriz - el valor ubicado en la fila 0 columna 2
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0,2])

3


In [25]:
# Extraer los valores de todas las filas ubicados en la columna 3 
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0:,2])

[3 5]


![linea 2](https://user-images.githubusercontent.com/19308295/115926262-2fb62980-a448-11eb-8189-c2f10e499944.png)

## <font color=#33A5FF>****4. Operaciones Matemáticas entre matrices de NumPy****<tfont>

**Valor mínimo, máximo y la suma de una matriz**

In [26]:
# Encontrar el mínimo, máximo y la suma
a= np.array([2,45,800])
print(a.min())
print(a.max())
print(a.sum())

2
800
847


**Raiz Cuadrada y Desviación de una matriz**

In [29]:
# Calcular la raíz cuadrada y la desviación estándar
a=np.array([(1,4,81),(33,44,50,)])
print(np.sqrt(a))
print(np.std(a))

[[1.         2.         9.        ]
 [5.74456265 6.63324958 7.07106781]]
27.5121185419565


**Suma, resta, multiplicación y división de dos matrices**

In [28]:
# Calcular la suma, resta, multiplicación y división de dos matrices
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x+y)
print()
print(x-y)
print()
print(x*y)
print()
print(x/y)

[[ 2  4  6]
 [ 6  8 10]]

[[0 0 0]
 [0 0 0]]

[[ 1  4  9]
 [ 9 16 25]]

[[1. 1. 1.]
 [1. 1. 1.]]
