<center> <h1>Universidad Nacional de San Agustín de Arequipa</h1> </center> 
<center> <h1>Escuela Profesional de Ingeniería de Telecomunicaciones</h1> </center> 

<center> <h1> </h1> </center> 

<center><img src="https://user-images.githubusercontent.com/19308295/115939517-f1c6fe80-a463-11eb-989c-812ab4942586.png" width="380" height="4200"></center>

<center> <h2>Ingeniero Renzo Bolivar - Docente DAIE</h2> </center> 
EMMANUEL ZAPATA MESTAS

###  Matriz  unidimensional

Con la primera instrucción `import numpy as np` le estamos indicando a nuestro programa de Python que de ahora en adelante `np` será la referencia para todo lo referente a NumPy.

In [1]:
import numpy as np
a=np.array([1,2,3])

print(a)

[1 2 3]


###  Matriz bidimensional

In [2]:
b=([(1,2,3),(4,5,6)])

print(b)

[(1, 2, 3), (4, 5, 6)]


In [3]:
array=np.array([[1,2,3,4],[5,6,7,8]], dtype=np.int64)

print(array)

[[1 2 3 4]
 [5 6 7 8]]


###  Porque usar NumPy

Porque usar NumPy en vez de utilizar las listas propias que ofrece Python para manejar estos datos, la primera razón es que NumPy ocupa menos memoria en comparación a las lista de Python, a su vez es bastante rápido en términos de ejecución. Lo que se observa en el siguiente ejemplo:

**Cantidad de memoria asignada**

In [4]:
import sys 
S=range(1000)
print(sys.getsizeof(5)*len(S))

28000


In [5]:
D=np.arange(1000)
print(D.size*D.itemsize)

4000


**Velocidad**

In [6]:
import time

SIZE = 1000000

L1= range(SIZE)
L2= range(SIZE)

start= time.time()
result= [(x,y) for x,y in zip(L1,L2)]  #Se usa "for"
print((time.time()-start)*1000)  #Velocidad en listas

145.29061317443848


In [7]:
A1= np.arange (SIZE)
A2= np.arange (SIZE)

start= time.time()
result= A1+A2     #Solo se suma
print((time.time()-start)*1000)  #Velocidad de Numpy

27.102231979370117


### Matrices Vacias

En ocasiones se requiere crear matrices vacías, esto se refiere a que se requieren marcadores de posición iniciales, que luego pueden ser rellenados. Se puede inicializar matrices con unos o ceros, pero también puedes hacer matrices que se llenan con valores espaciados uniformemente, valores constantes o aleatorios.

Algunas de las instrucciones para crear este tipo de matrices son las siguientes:

**Crear una matriz en donde todos los valores sean igual a 1**

In [8]:
# Crear una matriz de unos - 3 filas y 4 columnas
unos= np.ones((3,4))
print(unos)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**Crear una matriz en donde todos los valores sean igual a 0**

In [9]:
# Crear una matriz de ceros - 3 filas y 4 columnas
ceros= np.zeros((3,4))
print(ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Crear una matriz de números aleatorios**

In [10]:
# Crear una matriz con valores aleatorios
aleatorios = np.random.random((2,2))
print(aleatorios)

[[0.51000655 0.04748795]
 [0.17977088 0.03128048]]


**Crear una matriz vacía**

In [11]:
# Crear una matriz vacía
vacia= np.empty((3,2))
print(vacia)

[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 1.29061685e-306]
 [1.89146896e-307 7.56571288e-307]]


**Crear una matriz que contenga un solo valor en todas las posiciones**

In [12]:
# Crear una matriz con un solo valor
full= np.full((2,2),8)
print(full)

[[8 8]
 [8 8]]


**Crear una matriz con rangos de números**

In [13]:
# Crear una matriz con valores espaciados uniformemente
espacio1= np.arange(0,30,5)
print(espacio1)

[ 0  5 10 15 20 25]


In [14]:
espacio2= np.linspace(0,2,5)
print(espacio2)

[0.  0.5 1.  1.5 2. ]


**Crear una matriz identidad**

In [15]:
# Crear una matriz identidad
identidad1= np.eye(4,4)
print(identidad1)

identidad2= np.identity(4)
print(identidad2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


![linea 2](https://user-images.githubusercontent.com/19308295/115926262-2fb62980-a448-11eb-8189-c2f10e499944.png)

## <font color=#33A5FF>****3. Inspeccionar matrices de NumPy****<tfont>

**Dimensión de una matriz**

In [16]:
# Conocer las dimensiones de una matriz
a= np.array([(1,2,3),(4,5,6)])
print(a.ndim)

2


**Tipo de Datos de una matriz**

In [31]:
# Conocer el tipo de los datos
print(a.dtype)

int32


**Tamaño y forma de una matriz**

In [32]:
# Conocer el tamaño y forma de la matriz
a = np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)

6
(1, 6)


**Cambio de forma de una matriz**

In [33]:
# Cambio de forma de una matriz
a= np.array([(8,9,10),(11,12,13)])  # 2 filas x 3 columnas
print(a)
a= a.reshape(3,2)  # 3 filas x 2 columnas
print(a)

[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


**Seleccionar elemento de una matriz**

In [34]:
# Extraer un solo valor de la matriz - el valor ubicado en la fila 0 columna 2
a= np.array([(1,2,3,4),(3,4,5,6)])
print(a[0,2])

3


In [35]:
# Extraer los valores de todas las filas ubicados en la columna 3 
a= np.array([(1,2,3,4),(3,4,5,6)])
print(a[0:,2])

[3 5]


![linea 2](https://user-images.githubusercontent.com/19308295/115926262-2fb62980-a448-11eb-8189-c2f10e499944.png)

## <font color=#33A5FF>****4. Operaciones Matemáticas entre matrices de NumPy****<tfont>

**Valor mínimo, máximo y la suma de una matriz**

In [37]:
# Encontrar el mínimo, máximo y la suma
a= np.array([2,45,800])
print(a.min())
print(a.max())
print(a.sum())

2
800
847


**Raiz Cuadrada y Desviación de una matriz**

In [38]:
# Calcular la raíz cuadrada y la desviación estándar
a=np.array([(1,4,81),(33,44,50)])
print(np.sqrt(a))
print(np.std(a))

[[1.         2.         9.        ]
 [5.74456265 6.63324958 7.07106781]]
27.5121185419565


**Suma, resta, multiplicación y división de dos matrices**

In [40]:
# Calcular la suma, resta, multiplicación y división de dos matrices
x=np.array([(1,2,3),(3,4,5)])
y=np.array([(1,2,3),(3,4,5)])
print(x+y)
print()
print(x-y)
print()
print(x*y)
print()
print(x/y)

[[ 2  4  6]
 [ 6  8 10]]

[[0 0 0]
 [0 0 0]]

[[ 1  4  9]
 [ 9 16 25]]

[[1. 1. 1.]
 [1. 1. 1.]]


![linea 2](https://user-images.githubusercontent.com/19308295/115926262-2fb62980-a448-11eb-8189-c2f10e499944.png)

## <font color=#33A5FF>****EJEMPLOS****<tfont>

___Ejemplo 1:___ Cree una matriz de 5x5 con valores 1,2,3,4 justo debajo de la diagonal:

In [41]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


___Ejemplo 2:___ Crea un vector aleatorio de tamaño 30 y encuentra el valor medio :

In [42]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.6112883207131864


___Ejemplo 3:___ ¿Cómo ordenar una matriz por la enésima columna?:

In [43]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[5 5 5]
 [3 1 4]
 [4 9 0]]
[[3 1 4]
 [5 5 5]
 [4 9 0]]


___Ejemplo 4:___ ¿Cómo agregar un borde (lleno de 0) alrededor de una matriz existente?

In [44]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
