In [9]:
import numpy as np

# Create a random 5x5 matrix
matrix = np.random.randint(0, 50, (5, 5))

# Print the initial matrix
print(matrix)



[[ 9  7 27 33 26]
 [ 6 43 10 30 17]
 [12  7  3 11 25]
 [ 7  6  1  6 17]
 [17 42  9 35 23]]


In [7]:
# Find the minimum and maximum values
min_value = matrix.min()
max_value = matrix.max()

# Print the minimum and maximum values
print("\nValor mínimo:", min_value)
print("Valor máximo:", max_value)



Valor mínimo: 1
Valor máximo: 48


In [8]:
# Normalize the matrix between 0 and 1
normalized_matrix = (matrix - min_value) / (max_value - min_value)

# Print the normalized matrix
print("\nMatriz normalizada:")
print(normalized_matrix)


Matriz normalizada:
[[0.68085106 0.14893617 0.29787234 0.80851064 0.4893617 ]
 [0.04255319 0.85106383 0.57446809 0.57446809 0.89361702]
 [0.59574468 0.91489362 0.59574468 0.93617021 0.        ]
 [0.12765957 0.57446809 0.12765957 0.63829787 0.14893617]
 [0.63829787 0.29787234 0.19148936 1.         0.4893617 ]]
