In [2]:
import numpy as np

# Crear un vector de 10 elementos
vector = np.zeros(10, dtype=int)

# Asignar 1 a los índices impares
vector[::2] = 1

# Asignar 2 a los índices pares
vector[1::2] = 2

print(vector)

[1 2 1 2 1 2 1 2 1 2]


In [3]:
import numpy as np

# Crear un array 8x8 lleno de ceros
tablero = np.zeros((8, 8), dtype=int)

# Asignar 1 a las casillas negras
tablero[1::2, ::2] = 1
tablero[::2, 1::2] = 1

print(tablero)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
