In [1]:
# Primera matriz
import numpy as np
matriz1 = np.array([
    [255, 34, 45, 16, 24, 99],
    [200, 50, 67, 15, 56, 88],
    [165, 67, 34, 26, 87, 70],
    [120, 100, 45, 45, 56, 67],
    [45, 225, 35, 67, 50, 44],
    [36, 255, 24, 78, 77, 23]
])

# Segunda matriz
import numpy as np
matriz2 = np.array([
    [0, 0, 0],
    [0, 255, 0],
    [0, 0, 0]
])

# Encontrar la posición del valor 50 en la primera matriz
posiciones = np.argwhere(matriz1 == 50)

# Reemplazar con la segunda matriz en las posiciones encontradas
for pos in posiciones:
    fila, columna = pos
    matriz1[fila-1:fila+2, columna-1:columna+2] = matriz2

print(matriz1)

[[  0   0   0  16  24  99]
 [  0 255   0  15  56  88]
 [  0   0   0  26  87  70]
 [120 100  45   0   0   0]
 [ 45 225  35   0 255   0]
 [ 36 255  24   0   0   0]]
