In [1]:
import numpy as np

# Matriz original
original_matrix = np.array([
    [1, 1, 1, 1, 1],
    [1, 0, 0, 0, 1],
    [1, 0, 9, 0, 1],
    [1, 0, 0, 0, 1],
    [1, 0, 1, 1, 1]
])

# Crear una copia de la matriz original
modified_matrix = original_matrix.copy()

In [4]:
# Reemplazar todos los valores de 1 por -1 (valor temporal)
modified_matrix[modified_matrix == 1] = -1
print(modified_matrix)


[[-1 -1 -1 -1 -1]
 [-1  0  0  0 -1]
 [-1  0  9  0 -1]
 [-1  0  0  0 -1]
 [-1  0 -1 -1 -1]]


In [5]:
# Reemplazar todos los valores de 9 por 1
modified_matrix[modified_matrix == 9] = 1
print(modified_matrix)

[[-1 -1 -1 -1 -1]
 [-1  0  0  0 -1]
 [-1  0  1  0 -1]
 [-1  0  0  0 -1]
 [-1  0 -1 -1 -1]]


In [6]:
# Reemplazar todos los valores temporales (-1) por 9
modified_matrix[modified_matrix == -1] = 9
# Imprimir la matriz modificada
print("Matriz modificada:")
print(modified_matrix)

Matriz modificada:
[[9 9 9 9 9]
 [9 0 0 0 9]
 [9 0 1 0 9]
 [9 0 0 0 9]
 [9 0 9 9 9]]
