In [1]:
import numpy as np
array = np.zeros((7, 8), dtype=int)
print(array)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [2]:
import numpy as np
# Crear un array 7x8 lleno de ceros
array = np.zeros((7, 8), dtype=int)
# Establecer la primera fila a unos
array[0, :] = 1
print(array)

[[1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [1]:
import numpy as np

# Crear un array 7x8 lleno de ceros
array = np.zeros((7, 8), dtype=int)

# Establecer la última fila al rango entre 5 y 12
array[-1, :] = np.arange(5, 13)

print(array)

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 5  6  7  8  9 10 11 12]]
