Con la primera instrucción `import numpy as np` le estamos indicando a nuestro programa de Python que de ahora en adelante `np` será la referencia para todo lo referente a NumPy.

Porque usar NumPy en vez de utilizar las listas propias que ofrece Python para manejar estos datos, la primera razón es que NumPy ocupa menos memoria en comparación a las lista de Python, a su vez es bastante rápido en términos de ejecución. Lo que se observa en el siguiente ejemplo:

En ocasiones se requiere crear matrices vacías, esto se refiere a que se requieren marcadores de posición iniciales, que luego pueden ser rellenados. Se puede inicializar matrices con unos o ceros, pero también puedes hacer matrices que se llenan con valores espaciados uniformemente, valores constantes o aleatorios.

Algunas de las instrucciones para crear este tipo de matrices son las siguientes:

**Crear una matriz en donde todos los valores sean igual a 1**

<center> <h2>Ejercicio 05</h2> </center> 

De la siguiente Matriz:

<img src="https://user-images.githubusercontent.com/19308295/115969585-39509780-a503-11eb-92ac-fd88557e6cfc.png"
    style="width:400px"></img>

* Extraer la matrices de cada color

In [2]:
import numpy as np

matriz = np.arange(1, 31).reshape(6, 5)
#Seleccionando las matrices azul,rojoA y rojoB; en verde solo lo convierto en una matriz 4x4 y
#haciendo una copia para no modificar a las demas matrices
matriz_azul = matriz[2:4, 0:2]
matriz_rojoA = matriz[0:1, 3:5]
matriz_rojoB = matriz[4:6, 3:5]
matriz_verde = matriz[0:4, 1:5].copy()

#Solo para la matriz de verde: se conserva los numeros 2,8,14 y 20 los demas se convierten en ceros.
for n,m in np.ndindex(4,4):
  if matriz_verde[n,m] == 2:
    matriz_verde[n,m] = 2
  elif matriz_verde[n,m] == 8:
    matriz_verde[n,m] = 8
  elif matriz_verde[n,m] == 14:
    matriz_verde[n,m] = 14
  elif matriz_verde[n,m] == 20:
    matriz_verde[n,m] = 20
  else:
    matriz_verde[n,m] = 0

#Impresión
print("La matriz original es: ", end='\n\n')
print(matriz)
print("\n===============================")
print("Las matrices modificadas son: ", end='\n\n')
print("MATRIZ AZUL: ")
print(matriz_azul)
print("\nMATRIZ ROJO A: ")
print(matriz_rojoA)
print("\nMATRIZ ROJO B: ")
print(matriz_rojoB)
print("\nMATRIZ VERDE: ")
print(matriz_verde)

La matriz original es: 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

Las matrices modificadas son: 

MATRIZ AZUL: 
[[11 12]
 [16 17]]

MATRIZ ROJO A: 
[[4 5]]

MATRIZ ROJO B: 
[[24 25]
 [29 30]]

MATRIZ VERDE: 
[[ 2  0  0  0]
 [ 0  8  0  0]
 [ 0  0 14  0]
 [ 0  0  0 20]]


Se debe **buscar dentro de la matriz de color verde el valor = 50**, luego reemplazar con la pequeña matriz de color celeste quedando la matriz de la siguiente manera:

![linea 2](https://user-images.githubusercontent.com/19308295/115926262-2fb62980-a448-11eb-8189-c2f10e499944.png)

## <font color=#33A5FF>****BIBLIOGRAFÍA****<tfont>

[1] Documentación de NumPy http://docs.scipy.org/doc/numpy

[2] Travis Oliphant, "Guide to NumPy" http://csc.ucdavis.edu/~chaos/courses/nlp/Software/NumPyBook.pdf

[3] SciPy Lecture Notes http://scipy-lectures.github.io

[4] Nicolas Rougier, "100 NumPy exercises" http://www.loria.fr/~rougier/teaching/numpy.100/index.html

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)